<?php
/**
 * Created by PhpStorm.
 * User: kassymbekoff
 * Date: 28.11.2016
 * Time: 21:15
 */

namespace app\controllers\base;


use yii\rest\Controller;

/**
 * Class BaseController
 * @package app\controllers
 */
class BaseController extends Controller
{
    public function beforeAction($action)
    {
        if(\Yii::$app->request->isPost)
        {
            return parent::beforeAction($action); // TODO: Change the autogenerated stub
        }
        return false;
    }
}